// CloudSI UNTAN 2025 - 76 Members Data
// Photo URLs using DiceBear placeholder - ready to replace with real photos

import type { Member } from "./types";

export const MEMBERS_DATA_FULL: Member[] = [
  // === PENGURUS INTI ===
  {
    id: "1001",
    name: "Phasacola Grey Kalista",
    nim: "H1101251001",
    konsentrasi: "Software Engineer",
    email: "phasacola.grey@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Phasacola+Grey+Kalista",
    bio: "Ketua Angkatan CloudSI 2025. Berdedikasi membangun solidaritas dan memimpin dengan tanggung jawab.",
    divisi: "Digital & Kreatif",
    role: "Ketua Angkatan",
    social: {
      linkedin: "phasacola-grey",
      instagram: "@phasacola_grey",
      github: "https://github.com/phasacola",
    },
  },
  {
    id: "1002",
    name: "Rifkitio Hardiono",
    nim: "H1101251014",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "rifkitio.hardiono@untan.ac.id",
    photoUrl:
      "/members/1002.jpg",
    bio: "Wakil Ketua Angkatan CloudSI 2025, mendukung kepemimpinan dan koordinasi organisasi",
    divisi: "Digital & Kreatif",
    role: "Wakil Ketua",
    social: {
      linkedin: "rifkitio-hardiono",
      instagram: "@rifkitio_har",
      github: "https://github.com/rifkitio",
    },
  },
  {
    id: "1003",
    name: "Ellen Fitri Shanika Karrin Malau",
    nim: "H1101251027",
    konsentrasi: "Software Engineer",
    email: "ellen.fitri.shanika@untan.ac.id",
    photoUrl:
      "/members/1003.jpg",
    bio: "Sekretaris A CloudSI 2025, bertanggung jawab dalam administrasi",
    divisi: "Digital & Kreatif",
    role: "Sekretaris A",
    social: {
      linkedin: "ellen-fitri-shanika",
      instagram: "@ellen_fit",
      github: "https://github.com/ellen",
    },
  },
  {
    id: "1004",
    name: "Dhini Zakiyatul Wafa",
    nim: "H1101251020",
    konsentrasi: "IT Governance",
    email: "dhini.zakiyatul.wafa@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Dhini+Zakiyatul+Wafa",
    bio: "Sekretaris B CloudSI 2025, membantu dalam administrasi dan komunikasi",
    divisi: "Minat & Bakat",
    role: "Sekretaris B",
    social: {
      linkedin: "dhini-zakiyatul-wafa",
      instagram: "@dhini_waf",
      github: "https://github.com/dhini",
    },
  },
  {
    id: "1005",
    name: "Syarifah Putri",
    nim: "H1101251013",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "syarifah.putri@untan.ac.id",
    photoUrl: "/members/1005.jpg",
    bio: "Bendahara A CloudSI 2025, mengelola keuangan organisasi",
    divisi: "HUMAS",
    role: "Bendahara A",
    social: {
      linkedin: "syarifah-putri",
      instagram: "@syarifah_put",
      github: "https://github.com/syarifah",
    },
  },
  {
    id: "1006",
    name: "Andini Putri Malaya",
    nim: "H1101251052",
    konsentrasi: "IT Governance",
    email: "andini.putri.malaya@untan.ac.id",
    photoUrl:
      "/members/1006.jpg",
    bio: "Bendahara B CloudSI 2025, membantu pengelolaan keuangan",
    divisi: "Digital & Kreatif",
    role: "Bendahara B",
    social: {
      linkedin: "andini-putri-malaya",
      instagram: "@andini_put",
      github: "https://github.com/andini",
    },
  },

  // === KOORDINATOR DIVISI (3 Divisi) ===
  {
    id: "1007",
    name: "Najwa Aulia Putri",
    nim: "H1101251030",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "najwa.aulia.putri@untan.ac.id",
    photoUrl:
      "/members/1007.jpg",
    bio: "Koordinator Divisi Digital & Kreatif, mendorong inovasi dan kreativitas digital",
    divisi: "Digital & Kreatif",
    role: "Koordinator Divisi",
    social: {
      linkedin: "najwa-aulia-putri",
      instagram: "@najwa_aul",
      github: "https://github.com/najwa",
    },
  },
  {
    id: "1008",
    name: "Chayara Alima",
    nim: "H1101251056",
    konsentrasi: "IT Governance",
    email: "chayara.alima@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chayara+Alima",
    bio: "Koordinator Divisi Minat & Bakat, mengembangkan talenta anggota",
    divisi: "Minat & Bakat",
    role: "Koordinator Divisi",
    social: {
      linkedin: "chayara-alima",
      instagram: "@chayara_ali",
      github: "https://github.com/chayara",
    },
  },
  {
    id: "1009",
    name: "Ferdi",
    nim: "H1101251029",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "ferdi@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ferdi",
    bio: "Koordinator Divisi HUMAS, mengelola hubungan masyarakat dan komunikasi eksternal",
    divisi: "HUMAS",
    role: "Koordinator Divisi",
    social: {
      linkedin: "ferdi",
      instagram: "@ferdi_fer",
      github: "https://github.com/ferdi",
    },
  },

  // === ANGGOTA DIVISI DIGITAL & KREATIF ===
  {
    id: "1010",
    name: "Felix Faustine",
    nim: "H1101251045",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "felix.faustine@untan.ac.id",
    photoUrl: "/members/1010.jpg",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "felix-faustine",
      instagram: "@felix_fau",
      github: "https://github.com/felix",
    },
  },
  {
    id: "1011",
    name: "Nikoleta Febrina Listya Priyono",
    nim: "H1101251039",
    konsentrasi: "Software Engineer",
    email: "nikoleta.febrina.listy@untan.ac.id",
    photoUrl:
      "/members/1011.jpg",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "nikoleta-febrina-listy",
      instagram: "@nikoleta_feb",
      github: "https://github.com/nikoleta",
    },
  },
  {
    id: "1012",
    name: "Khairunisa Ansyari Ramadhan",
    nim: "H1101251057",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "khairunisa.ansyari@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Khairunisa+Ansyari",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "khairunisa-ansyari",
      instagram: "@khairunisa_ans",
      github: "https://github.com/khairunisa",
    },
  },
  {
    id: "1013",
    name: "Fitri Amelia Oktaviani",
    nim: "H1101251054",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "fitri.amelia.oktaviani@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Fitri+Amelia+Oktaviani",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "fitri-amelia-oktaviani",
      instagram: "@fitri_ame",
      github: "https://github.com/fitri",
    },
  },
  {
    id: "1014",
    name: "Sri Wahyuni",
    nim: "H1101251006",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "sri.wahyuni@untan.ac.id",
    photoUrl: "/members/1014.jpg",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "sri-wahyuni",
      instagram: "@sri_wah",
      github: "https://github.com/sri",
    },
  },
  {
    id: "1015",
    name: "Desty Ayudya",
    nim: "H1101251023",
    konsentrasi: "Software Engineer",
    email: "desty.ayudya@untan.ac.id",
    photoUrl: "/members/1015.jpg",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "desty-ayudya",
      instagram: "@desty_ayu",
      github: "https://github.com/desty",
    },
  },
  {
    id: "1016",
    name: "Nasywa Akmalia Hanif",
    nim: "H1101251010",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "nasywa.akmalia.hanif@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Nasywa+Akmalia+Hanif",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "nasywa-akmalia-hanif",
      instagram: "@nasywa_han",
      github: "https://github.com/nasywa",
    },
  },
  {
    id: "1017",
    name: "Nova Amelia",
    nim: "H1101251002",
    konsentrasi: "Software Engineer",
    email: "nova.amelia@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nova+Amelia",
    bio: "Anggota Divisi Digital & Kreatif CloudSI 2025",
    divisi: "Digital & Kreatif",
    role: "Anggota Divisi",
    social: {
      linkedin: "nova-amelia",
      instagram: "@nova_ame",
      github: "https://github.com/nova",
    },
  },

  // === ANGGOTA DIVISI MINAT & BAKAT ===
  {
    id: "1018",
    name: "Vita Ervina Dzalfa",
    nim: "H1101251071",
    konsentrasi: "Software Engineer",
    email: "vita.ervina.dzalfa@untan.ac.id",
    photoUrl:
      "/members/1018.jpg",
    bio: "Anggota Divisi Minat & Bakat CloudSI 2025",
    divisi: "Minat & Bakat",
    role: "Anggota Divisi",
    social: {
      linkedin: "vita-ervina-dzalfa",
      instagram: "@vita_erv",
      github: "https://github.com/vita",
    },
  },
  {
    id: "1019",
    name: "Lika Lidia Astutik",
    nim: "H1101251059",
    konsentrasi: "Software Engineer",
    email: "lika.lidia.astutik@untan.ac.id",
    photoUrl:
      "/members/1019.jpg",
    bio: "Anggota Divisi Minat & Bakat CloudSI 2025",
    divisi: "Minat & Bakat",
    role: "Anggota Divisi",
    social: {
      linkedin: "lika-lidia-astutik",
      instagram: "@lika_lid",
      github: "https://github.com/lika",
    },
  },
  {
    id: "1020",
    name: "Syarif Hizra Muhammad Zacky",
    nim: "H1101251031",
    konsentrasi: "Software Engineer",
    email: "syarif.hizra.zacky@untan.ac.id",
    photoUrl:
      "/members/1020.jpg",
    bio: "Anggota Divisi Minat & Bakat CloudSI 2025",
    divisi: "Minat & Bakat",
    role: "Anggota Divisi",
    social: {
      linkedin: "syarif-hizra-zacky",
      instagram: "@syarif_hiz",
      github: "https://github.com/syarif",
    },
  },

  // === ANGGOTA DIVISI HUMAS ===
  {
    id: "1021",
    name: "Aldan Putra Setiawan",
    nim: "H1101251046",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "aldan.putra.setiawan@untan.ac.id",
    photoUrl:
      "/members/1021.jpg",
    bio: "Anggota Divisi HUMAS CloudSI 2025",
    divisi: "HUMAS",
    role: "Anggota Divisi",
    social: {
      linkedin: "aldan-putra-setiawan",
      instagram: "@aldan_put",
      github: "https://github.com/aldan",
    },
  },
  {
    id: "1022",
    name: "Zahratussita",
    nim: "H1101251044",
    konsentrasi: "IT Governance",
    email: "zahratussita@untan.ac.id",
    photoUrl: "/members/1022.jpg",
    bio: "Anggota Divisi HUMAS CloudSI 2025",
    divisi: "HUMAS",
    role: "Anggota Divisi",
    social: {
      linkedin: "zahratussita",
      instagram: "@zahratuss",
      github: "https://github.com/zahratussita",
    },
  },
  {
    id: "1023",
    name: "Muhammad Ghifari Rubiyanto",
    nim: "H1101251022",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "ghifari.rubiyanto@untan.ac.id",
    photoUrl:
      "/members/1023.jpg",
    bio: "Anggota Divisi HUMAS CloudSI 2025",
    divisi: "HUMAS",
    role: "Anggota Divisi",
    social: {
      linkedin: "ghifari-rubiyanto",
      instagram: "@ghifari_rub",
      github: "https://github.com/ghifari",
    },
  },

  // === ANGGOTA BIASA (tidak di divisi manapun / belum bergabung) ===
  {
    id: "1024",
    name: "M. Sholichin Tafsir Srilintang",
    nim: "H1101251016",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "sholichin.tafsir@untan.ac.id",
    photoUrl:
      "/members/1024.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "sholichin-tafsir",
      instagram: "@srilintang_",
      github: "https://github.com/sholichin",
    },
  },
  {
    id: "1025",
    name: "M. Hafizh Al Fitra",
    nim: "H1101251003",
    konsentrasi: "IT Governance",
    email: "hafizh.al.fitra@untan.ac.id",
    photoUrl: "/members/1025.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "hafizh-al-fitra",
      instagram: "@hafizh_fit",
      github: "https://github.com/hafizh",
    },
  },
  {
    id: "1026",
    name: "Dimas Luthfi Salim",
    nim: "H1101251004",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "dimas.luthfi.salim@untan.ac.id",
    photoUrl:
      "/members/1026.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "dimas-luthfi-salim",
      instagram: "@dimas_sal",
      github: "https://github.com/dimas",
    },
  },
  {
    id: "1027",
    name: "Neisya Fadilla",
    nim: "H1101251007",
    konsentrasi: "Software Engineer",
    email: "neisya.fadilla@untan.ac.id",
    photoUrl: "/members/1027.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "neisya-fadilla",
      instagram: "@neisya_fad",
      github: "https://github.com/neisya",
    },
  },
  {
    id: "1028",
    name: "Akmal Pasha",
    nim: "H1101251008",
    konsentrasi: "IT Governance",
    email: "akmal.pasha@untan.ac.id",
    photoUrl: "/members/1028.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "akmal-pasha",
      instagram: "@akmal_pas",
      github: "https://github.com/akmal",
    },
  },
  {
    id: "1029",
    name: "Fahriello Ardhayana",
    nim: "H1101251009",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "fahriello.ardhayana@untan.ac.id",
    photoUrl:
      "/members/1029.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "fahriello-ardhayana",
      instagram: "@fahriello_ard",
      github: "https://github.com/fahriello",
    },
  },
  {
    id: "1030",
    name: "Gendis Setyawan",
    nim: "H1101251011",
    konsentrasi: "Software Engineer",
    email: "gendis.setyawan@untan.ac.id",
    photoUrl: "/members/1030.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "gendis-setyawan",
      instagram: "@gendis_set",
      github: "https://github.com/gendis",
    },
  },
  {
    id: "1031",
    name: "Charles Wong",
    nim: "H1101251012",
    konsentrasi: "IT Governance",
    email: "charles.wong@untan.ac.id",
    photoUrl: "/members/1031.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "charles-wong",
      instagram: "@charles_won",
      github: "https://github.com/charles",
    },
  },
  {
    id: "1032",
    name: "Ahmad Rahman",
    nim: "H1101251015",
    konsentrasi: "Software Engineer",
    email: "ahmad.rahman@untan.ac.id",
    photoUrl: "/members/1032.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "ahmad-rahman",
      instagram: "@ahmad_rah",
      github: "https://github.com/ahmad",
    },
  },
  {
    id: "1033",
    name: "M. Hizbullah Pohan",
    nim: "H1101251017",
    konsentrasi: "IT Governance",
    email: "hizbullah.pohan@untan.ac.id",
    photoUrl: "/members/1033.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "hizbullah-pohan",
      instagram: "@hizbullah_poh",
      github: "https://github.com/hizbullah",
    },
  },
  {
    id: "1034",
    name: "Tiara Maritza",
    nim: "H1101251018",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "tiara.maritza@untan.ac.id",
    photoUrl: "/members/1034.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "tiara-maritza",
      instagram: "@tiara_mar",
      github: "https://github.com/tiara",
    },
  },
  {
    id: "1035",
    name: "Shinta Ayuwidati",
    nim: "H1101251019",
    konsentrasi: "Software Engineer",
    email: "shinta.ayuwidati@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Shinta+Ayuwidati",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "shinta-ayuwidati",
      instagram: "@shinta_ayu",
      github: "https://github.com/shinta",
    },
  },
  {
    id: "1036",
    name: "M. Iqbal Dzakwani",
    nim: "H1101251021",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "iqbal.dzakwani@untan.ac.id",
    photoUrl: "/members/1036.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "iqbal-dzakwani",
      instagram: "@iqbal_dza",
      github: "https://github.com/iqbal",
    },
  },
  {
    id: "1037",
    name: "Uray Diana",
    nim: "H1101251024",
    konsentrasi: "IT Governance",
    email: "uray.diana@untan.ac.id",
    photoUrl: "/members/1037.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "uray-diana",
      instagram: "@uray_dia",
      github: "https://github.com/uray",
    },
  },
  {
    id: "1038",
    name: "Lia Rarasari",
    nim: "H1101251025",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "lia.rarasari@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lia+Rarasari",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "lia-rarasari",
      instagram: "@lia_rar",
      github: "https://github.com/lia",
    },
  },
  {
    id: "1039",
    name: "Derriel Mulya Ramadhan",
    nim: "H1101251026",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "derriel.mulya.ramadhan@untan.ac.id",
    photoUrl: "/members/1039.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "derriel-mulya-ramadhan",
      instagram: "@derriel_mul",
      github: "https://github.com/derriel",
    },
  },
  {
    id: "1040",
    name: "Utin Dita Atyana",
    nim: "H1101251028",
    konsentrasi: "IT Governance",
    email: "utin.dita.atyana@untan.ac.id",
    photoUrl:
      "/members/1040.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "utin-dita-atyana",
      instagram: "@utin_dit",
      github: "https://github.com/utin",
    },
  },
  {
    id: "1041",
    name: "Rezki Firmansyah",
    nim: "H1101251032",
    konsentrasi: "IT Governance",
    email: "rezki.firmansyah@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Rezki+Firmansyah",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "rezki-firmansyah",
      instagram: "@rezki_fir",
      github: "https://github.com/rezki",
    },
  },
  {
    id: "1042",
    name: "Alfonsius Pernandes Roby",
    nim: "H1101251033",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "alfonsius.pernandes.roby@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Alfonsius+Pernandes",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "alfonsius-pernandes-roby",
      instagram: "@alfonsius_per",
      github: "https://github.com/alfonsius",
    },
  },
  {
    id: "1043",
    name: "Chelsea Zalianti",
    nim: "H1101251034",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "chelsea.zalianti@untan.ac.id",
    photoUrl:
      "/members/1043.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "chelsea-zalianti",
      instagram: "@chelsea_zal",
      github: "https://github.com/chelsea",
    },
  },
  {
    id: "1044",
    name: "M. Farras Haidar",
    nim: "H1101251035",
    konsentrasi: "Software Engineer",
    email: "farras.haidar@untan.ac.id",
    photoUrl: "/members/1044.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "farras-haidar",
      instagram: "@farras_hai",
      github: "https://github.com/farras",
    },
  },
  {
    id: "1045",
    name: "Deslo Aldo Anggoro",
    nim: "H1101251036",
    konsentrasi: "IT Governance",
    email: "deslo.aldo.anggoro@untan.ac.id",
    photoUrl: "/members/1045.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "deslo-aldo-anggoro",
      instagram: "@deslo_ald",
      github: "https://github.com/deslo",
    },
  },
  {
    id: "1046",
    name: "Mercello Januarius Erick",
    nim: "H1101251038",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "mercello.januarius.erick@untan.ac.id",
    photoUrl:
      "/members/1046.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "mercello-januarius-erick",
      instagram: "@mercello_jan",
      github: "https://github.com/mercello",
    },
  },
  {
    id: "1047",
    name: "Nabila Pracita Ramadhanti",
    nim: "H1101251040",
    konsentrasi: "IT Governance",
    email: "nabila.pracita.ramadhanti@untan.ac.id",
    photoUrl: "/members/1047.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "nabila-pracita-ramadhanti",
      instagram: "@nabila_prac",
      github: "https://github.com/nabila",
    },
  },
  {
    id: "1048",
    name: "Rasya Akmal Sakhi",
    nim: "H1101251041",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "rasya.akmal.sakhi@untan.ac.id",
    photoUrl: "/members/1048.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "rasya-akmal-sakhi",
      instagram: "@rasya_akm",
      github: "https://github.com/rasya",
    },
  },
  {
    id: "1049",
    name: "Riton Stefano",
    nim: "H1101251042",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "riton.stefano@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Riton+Stefano",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "riton-stefano",
      instagram: "@riton_ste",
      github: "https://github.com/riton",
    },
  },
  {
    id: "1050",
    name: "Novi Aulia",
    nim: "H1101251043",
    konsentrasi: "Software Engineer",
    email: "novi.aulia@untan.ac.id",
    photoUrl: "/members/1050.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "novi-aulia",
      instagram: "@novi_aul",
      github: "https://github.com/novi",
    },
  },
  {
    id: "1051",
    name: "Melly",
    nim: "H1101251047",
    konsentrasi: "Software Engineer",
    email: "melly@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Melly",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "melly",
      instagram: "@melly_mel",
      github: "https://github.com/melly",
    },
  },
  {
    id: "1052",
    name: "Hubert Melville Prince M.",
    nim: "H1101251048",
    konsentrasi: "IT Governance",
    email: "hubert.melville.prince@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hubert+Melville",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "hubert-melville-prince",
      instagram: "@hubert_mel",
      github: "https://github.com/hubert",
    },
  },
  {
    id: "1053",
    name: "Raihan Ikram M.",
    nim: "H1101251049",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "raihan.ikram@untan.ac.id",
    photoUrl: "/members/1053.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "raihan-ikram",
      instagram: "@raihan_ikr",
      github: "https://github.com/raihan",
    },
  },
  {
    id: "1054",
    name: "Wilham Dhani Prasetyo",
    nim: "H1101251050",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "wilham.dhani.prasetyo@untan.ac.id",
    photoUrl: "/members/1054.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "wilham-dhani-prasetyo",
      instagram: "@wilham_dha",
      github: "https://github.com/wilham",
    },
  },
  {
    id: "1055",
    name: "Adli Anara Sofian",
    nim: "H1101251051",
    konsentrasi: "Software Engineer",
    email: "adli.anara.sofian@untan.ac.id",
    photoUrl: "/members/1055.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "adli-anara-sofian",
      instagram: "@adli_ana",
      github: "https://github.com/adli",
    },
  },
  {
    id: "1056",
    name: "Velixza Gracia E.",
    nim: "H1101251053",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "velixza.gracia@untan.ac.id",
    photoUrl: "/members/1056.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "velixza-gracia",
      instagram: "@velixza_gra",
      github: "https://github.com/velixza",
    },
  },
  {
    id: "1057",
    name: "Aiffy Ragta A.",
    nim: "H1101251055",
    konsentrasi: "Software Engineer",
    email: "aiffy.ragta@untan.ac.id",
    photoUrl: "/members/1057.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "aiffy-ragta",
      instagram: "@aiffy_rag",
      github: "https://github.com/aiffy",
    },
  },
  {
    id: "1058",
    name: "Salsabilla Fitri Nur R.",
    nim: "H1101251058",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "salsabilla.fitri.nur@untan.ac.id",
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Salsabilla+Fitri",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "salsabilla-fitri-nur",
      instagram: "@salsabilla_fit",
      github: "https://github.com/salsabilla",
    },
  },
  {
    id: "1059",
    name: "M. Dimas Aditya",
    nim: "H1101251060",
    konsentrasi: "IT Governance",
    email: "dimas.aditya@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dimas+Aditya",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "dimas-aditya",
      instagram: "@dimas_adi",
      github: "https://github.com/dimas",
    },
  },
  {
    id: "1060",
    name: "Rizqi Ikhwani",
    nim: "H1101251061",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "rizqi.ikhwani@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rizqi+Ikhwani",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "rizqi-ikhwani",
      instagram: "@rizqi_ikh",
      github: "https://github.com/rizqi",
    },
  },
  {
    id: "1061",
    name: "Iren Meiliani Taslim",
    nim: "H1101251062",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "iren.meiliani.taslim@untan.ac.id",
    photoUrl: "/members/1061.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "iren-meiliani-taslim",
      instagram: "@iren_mei",
      github: "https://github.com/iren",
    },
  },
  {
    id: "1062",
    name: "Maulana Malik Ibrahim",
    nim: "H1101251063",
    konsentrasi: "Software Engineer",
    email: "maulana.malik.ibrahim@untan.ac.id",
    photoUrl: "/members/1062.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "maulana-malik-ibrahim",
      instagram: "@maulana_mal",
      github: "https://github.com/maulana",
    },
  },
  {
    id: "1063",
    name: "Elki Donggala",
    nim: "H1101251064",
    konsentrasi: "IT Governance",
    email: "elki.donggala@untan.ac.id",
    photoUrl: "/members/1063.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "elki-donggala",
      instagram: "@elki_don",
      github: "https://github.com/elki",
    },
  },
  {
    id: "1064",
    name: "Riko",
    nim: "H1101251065",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "riko@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Riko",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "riko",
      instagram: "@riko_rik",
      github: "https://github.com/riko",
    },
  },
  {
    id: "1065",
    name: "Andini Salsabilla",
    nim: "H1101251066",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "andini.salsabilla@untan.ac.id",
    photoUrl:
      "/members/1065.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "andini-salsabilla",
      instagram: "@andini_sal",
      github: "https://github.com/andini",
    },
  },
  {
    id: "1066",
    name: "Luqmanurhakim",
    nim: "H1101251067",
    konsentrasi: "Software Engineer",
    email: "luqmanurhakim@untan.ac.id",
    photoUrl: "/members/1066.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "luqmanurhakim",
      instagram: "@luqman_urh",
      github: "https://github.com/luqmanurhakim",
    },
  },
  {
    id: "1067",
    name: "Zuhayr Aljabar",
    nim: "H1101251068",
    konsentrasi: "IT Governance",
    email: "zuhayr.aljabar@untan.ac.id",
    photoUrl: "/members/1067.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "zuhayr-aljabar",
      instagram: "@zuhayr_alj",
      github: "https://github.com/zuhayr",
    },
  },
  {
    id: "1068",
    name: "Chattama Albiantoro",
    nim: "H1101251069",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "chattama.albiantoro@untan.ac.id",
    photoUrl:
      "/members/1068.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "chattama-albiantoro",
      instagram: "@chattama_alb",
      github: "https://github.com/chattama",
    },
  },
  {
    id: "1069",
    name: "Khalindra Maulita S.",
    nim: "H1101251070",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "khalindra.maulita@untan.ac.id",
    photoUrl:
      "/members/1069.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "khalindra-maulita",
      instagram: "@khalindra_mau",
      github: "https://github.com/khalindra",
    },
  },
  {
    id: "1070",
    name: "Alnelka Parisha N.",
    nim: "H1101251072",
    konsentrasi: "IT Governance",
    email: "alnelka.parisha@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alnelka+Parisha",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "alnelka-parisha",
      instagram: "@alnelka_par",
      github: "https://github.com/alnelka",
    },
  },
  {
    id: "1071",
    name: "Ibnu Khaidir Rahman",
    nim: "H1101251073",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "ibnu.khaidir.rahman@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ibnu+Khaidir",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "ibnu-khaidir-rahman",
      instagram: "@ibnu_kha",
      github: "https://github.com/ibnu",
    },
  },
  {
    id: "1072",
    name: "Bona Tua Sagala",
    nim: "H1101251074",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "bona.tua.sagala@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bona+Tua+Sagala",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "bona-tua-sagala",
      instagram: "@bona_tua",
      github: "https://github.com/bona",
    },
  },
  {
    id: "1073",
    name: "Maulana Ardhi",
    nim: "H1101251075",
    konsentrasi: "Software Engineer",
    email: "maulana.ardhi@untan.ac.id",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maulana+Ardhi",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "maulana-ardhi",
      instagram: "@maulana_ard",
      github: "https://github.com/maulana",
    },
  },
  {
    id: "1074",
    name: "Pierre Tristan L.",
    nim: "H1101251076",
    konsentrasi: "IT Governance",
    email: "pierre.tristan@untan.ac.id",
    photoUrl: "/members/1074.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "pierre-tristan",
      instagram: "@pierre_tris",
      github: "https://github.com/pierre",
    },
  },
  {
    id: "1075",
    name: "Indra Prianto",
    nim: "H1101251077",
    konsentrasi: "Data Analyst Dan Bisnis Digital",
    email: "indra.prianto@untan.ac.id",
    photoUrl: "/members/1075.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "indra-prianto",
      instagram: "@indra_pri",
      github: "https://github.com/indra",
    },
  },
  {
    id: "1076",
    name: "Febriano Farrel Naufal",
    nim: "H1101251078",
    konsentrasi: "Cloud Infrastructure & DevOps",
    email: "febriano.farrel.naufal@untan.ac.id",
    photoUrl: "/members/1076.jpg",
    bio: "Mahasiswa Sistem Informasi UNTAN 2025",
    divisi: "Belum Bergabung",
    role: "Anggota",
    social: {
      linkedin: "febriano-farrel-naufal",
      instagram: "@febriano_far",
      github: "https://github.com/febriano",
    },
  },
];
